### ISSUE TITLE
[Customer]xcat 2.9.2 does not work with AIX7.2

### ISSUE THREAD

**Issue by bankabanka** [xcat2/xcat-core#546]
Getting the following error when running powerstatus or poweron after upgrading AIX 7.2 and xCat 2.9.2.

Can't locate XML/Simple.pm in @INC (you may need to install the XML::Simple module) 
(@INC contains: /opt/xcat/lib/perl /usr/opt/perl5/lib/5.8.2/aix-thread-multi /usr/op
t/perl5/lib/5.8.2 /usr/opt/perl5/lib/site_perl/5.8.2/aix-thread-multi /usr/opt/perl5
/lib/site_perl/5.8.2 /usr/opt/perl5/lib/site_perl/5.8.2/aix-thread-multi  /usr/opt/p
erl5/lib/site_perl/5.20.1/aix-thread-multi /usr/opt/perl5/lib/site_perl/5.20.1 /usr/
opt/perl5/lib/5.20.1/aix-thread-multi /usr/opt/perl5/lib/5.20.1 /usr/opt/perl5/lib/s
ite_perl .) at /opt/xcat/lib/perl/xCAT/Client.pm line 45.
BEGIN failed--compilation aborted at /opt/xcat/lib/perl/xCAT/Client.pm line 45.
Compilation failed in require at /opt/xcat/bin/rpower line 18.
BEGIN failed--compilation aborted at /opt/xcat/bin/rpower line 18.

**Comment by daniceexi** [comment]
xCAT team is trying to recreate this issue.

**Comment by tingtli** [comment]
@bankabanka  Please try xcat 2.9.3 release to see if it fixes your problem. If yes, please close it. Thanks!
