### ISSUE TITLE
[DEV]syntax error in " /opt/xcat//lib/perl//xCAT/PPC.pm"

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#2490]
````
[root@c910f02c09p09 ~]# perl -I /opt/xcat//lib/perl/ -c  /opt/xcat/lib/perl/xCAT_plugin/bpa.pm
Global symbol "$subcmd" requires explicit package name at /opt/xcat//lib/perl//xCAT/PPC.pm line 238.
Global symbol "$subcmd" requires explicit package name at /opt/xcat//lib/perl//xCAT/PPC.pm line 238.
Global symbol "$subcmd" requires explicit package name at /opt/xcat//lib/perl//xCAT/PPC.pm line 238.
BEGIN not safe after errors--compilation aborted at /opt/xcat//lib/perl//xCAT/PPC.pm line 1790.
Compilation failed in require at /opt/xcat/lib/perl/xCAT_plugin/bpa.pm line 5.
BEGIN failed--compilation aborted at /opt/xcat/lib/perl/xCAT_plugin/bpa.pm line 5.
````

**Comment by immarvin** [comment]
hi @cxhong , this issue might be caused by the PR https://github.com/xcat2/xcat-core/pull/2481

**Comment by cxhong** [comment]
Thanks, YangSong.

**Comment by cxhong** [comment]
will close this issue
